package aigit

import (
	"context"
	"fmt"
	"strings"

	"github.com/spf13/cobra"
)

type Cli struct {
	model  Model
	git    Git
	github GitHub
	root   *cobra.Command
}

func NewCli(model Model, git Git, github GitHub) *Cli {
	cli := &Cli{
		model:  model,
		git:    git,
		github: github,
	}

	cli.root = &cobra.Command{
		Use:   "aigit",
		Short: "AI-enhanced git CLI",
		Long:  `A git CLI tool that uses AI to help with common git operations.`,
	}

	commitCmd := &cobra.Command{
		Use:   "commit",
		Short: "Create a commit with an AI-generated message",
		Long:  `Create a commit with a message generated by AI based on the staged changes.`,
		RunE:  cli.commit,
	}

	prCmd := &cobra.Command{
		Use:   "pr",
		Short: "Create a pull request with an AI-generated description",
		Long:  `Create a pull request with a description generated by AI based on the commit history.`,
		RunE:  cli.createPR,
	}

	cli.root.AddCommand(commitCmd)
	cli.root.AddCommand(prCmd)
	return cli
}

func (cli *Cli) Run(args []string) error {
	cli.root.SetArgs(args[1:]) // Skip the program name
	return cli.root.Execute()
}

// cleanMarkdownCodeBlocks removes markdown code block markers from the text
func cleanMarkdownCodeBlocks(text string) string {
	// Remove ``` at the start and end of the text
	text = strings.TrimSpace(text)
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")
	return strings.TrimSpace(text)
}

func (cli *Cli) commit(cmd *cobra.Command, args []string) error {
	// Get staged changes
	diff, err := cli.git.GetStagedDiff()
	if err != nil {
		return fmt.Errorf("error getting staged changes: %w", err)
	}

	if diff == "" {
		return fmt.Errorf("no changes staged for commit")
	}

	// Ask AI for commit message
	query := fmt.Sprintf("Please write a concise and descriptive commit message, adhering to conventional commits and in plain text, for the following changes:\n\n%s", diff)
	message, err := cli.model.Query(context.Background(), query)
	if err != nil {
		return fmt.Errorf("error getting commit message from AI: %w", err)
	}

	// Clean up the message
	message = cleanMarkdownCodeBlocks(message)

	// Execute git commit
	if err := cli.git.Commit(message); err != nil {
		return fmt.Errorf("error committing changes: %w", err)
	}

	fmt.Printf("Committed with message:\n%s\n", message)
	return nil
}

func (cli *Cli) createPR(cmd *cobra.Command, args []string) error {
	// Get current branch
	currentBranch, err := cli.git.GetCurrentBranch()
	if err != nil {
		return fmt.Errorf("error getting current branch: %w", err)
	}

	// Get base branch
	baseBranch, err := cli.git.GetBaseBranch()
	if err != nil {
		return fmt.Errorf("error getting base branch: %w", err)
	}

	// Get commit history
	history, err := cli.git.GetCommitHistory(baseBranch)
	if err != nil {
		return fmt.Errorf("error getting commit history: %w", err)
	}

	if history == "" {
		return fmt.Errorf("no commits found between %s and %s", baseBranch, currentBranch)
	}

	// Ask AI for PR description
	query := fmt.Sprintf("Please write a concise and descriptive pull request description for the following changes. Include a summary of the changes and any important notes for reviewers:\n\n%s", history)
	description, err := cli.model.Query(context.Background(), query)
	if err != nil {
		return fmt.Errorf("error getting PR description from AI: %w", err)
	}

	// Clean up the description
	description = cleanMarkdownCodeBlocks(description)

	// Create PR title from the first line of the description
	title := strings.Split(description, "\n")[0]

	// Create the pull request
	if err := cli.github.CreatePullRequest(title, description); err != nil {
		return fmt.Errorf("error creating pull request: %w", err)
	}

	fmt.Printf("Created pull request with title:\n%s\n", title)
	return nil
}
